/* Unit tests for the AUTOSAR SWC AEB_Core_SWC (generated by Embedded Coder).
 * The SWC is exercised only through its RTE ports, like on the ECU.
 * Requirement IDs refer to docs/requirements.md. */
#include <math.h>
#include "AEB_Core_SWC.h"
#include "rte_test_double.h"
#include "mini_junit.h"

#define DT 0.01   /* runnable period [s] (10 ms) */

/* One 10 ms task: set RTE inputs, run the runnable. */
static void step(double relDist, double latOff, double relVel, double egoVel)
{
  rte_in.RelDistance = relDist;
  rte_in.LeadLatOffset = latOff;
  rte_in.RelVelocity = relVel;
  rte_in.EgoVelocity = egoVel;
  AEB_Core_SWC_Step();
}

static void fresh_ecu(void)
{
  /* Static memory starts at zero on a real ECU after reset. */
  memset(&AEB_Core_SWC_ARID_DEF, 0, sizeof(AEB_Core_SWC_ARID_DEF));
  Rte_TestDouble_Reset();
  AEB_Core_SWC_Init();
}

/* Closed loop: ego brakes with the SWC's deceleration command, no driver. */
typedef struct {
  double maxDecel;      /* most negative decel seen (as positive number) */
  double minGap;        /* smallest RelDistance seen [m]                 */
  double finalEgoV;
  int stageOrderOk;     /* decel never skipped a stage                   */
  int anyTrigger;
  int triggerAtEnd;
  double decelAtEnd;
} loop_result_t;

static int stage_of(double decel)
{
  if (decel == 0.0) return 0;
  if (decel == -3.8) return 2;
  if (decel == -5.3) return 3;
  if (decel == -9.8) return 4;
  return -1;
}

static loop_result_t closed_loop(double leadX, double leadV, double egoV,
                                 double latOff, double seconds)
{
  loop_result_t r;
  double egoX = 0.0, gap;
  int k, n = (int)(seconds / DT), prevStage = 0;
  fresh_ecu();
  r.maxDecel = 0.0; r.minGap = 1e9; r.stageOrderOk = 1; r.anyTrigger = 0;
  for (k = 0; k < n; k++) {
    int s;
    gap = leadX - egoX;
    if (gap < r.minGap) r.minGap = gap;
    step(gap, latOff, leadV - egoV, egoV);
    s = stage_of(rte_out.Deceleration);
    if (s < 0 || (s > prevStage && s != 2 && s != prevStage + 1)) r.stageOrderOk = 0;
    if (s > 0) prevStage = s;
    if (s == 0) prevStage = 0;
    if (-rte_out.Deceleration > r.maxDecel) r.maxDecel = -rte_out.Deceleration;
    if (rte_out.AEBTrigger != 0.0) r.anyTrigger = 1;
    egoV += rte_out.Deceleration * DT;
    if (egoV < 0.0) egoV = 0.0;
    egoX += egoV * DT;
    leadX += leadV * DT;
  }
  r.finalEgoV = egoV;
  r.triggerAtEnd = rte_out.AEBTrigger != 0.0;
  r.decelAtEnd = rte_out.Deceleration;
  return r;
}

/* REQ-01 */
static void t_no_action_when_far(void)
{
  int k;
  fresh_ecu();
  for (k = 0; k < 100; k++) {
    step(150.0, 0.0, -10.0, 20.0);    /* TTC 14.6 s > FCW time 6.2 s */
    MJ_CHECK(rte_out.AEBTrigger == 0.0, "trigger=%g at k=%d", rte_out.AEBTrigger, k);
    MJ_CHECK(rte_out.Deceleration == 0.0, "decel=%g at k=%d", rte_out.Deceleration, k);
  }
}

/* REQ-02 */
static void t_no_action_when_lead_pulls_away(void)
{
  loop_result_t r = closed_loop(10.0, 25.0, 20.0, 0.0, 5.0);
  MJ_CHECK(!r.anyTrigger, "trigger raised while lead pulls away");
  MJ_CHECK(r.maxDecel == 0.0, "braked %.1f m/s2 while lead pulls away", r.maxDecel);
}

/* REQ-03 */
static void t_fcw_before_braking(void)
{
  int k, fcwSeen = 0;
  fresh_ecu();
  for (k = 0; k < 400; k++) {
    double gap = 150.0 - 20.0 * DT * k;   /* stationary lead, ego 20 m/s */
    step(gap, 0.0, -20.0, 20.0);
    if (rte_out.AEBTrigger != 0.0 && rte_out.Deceleration == 0.0) fcwSeen = 1;
    if (rte_out.Deceleration < 0.0) {
      MJ_CHECK(fcwSeen, "braking started at gap %.2f m without FCW first", gap);
      break;
    }
  }
  MJ_CHECK(fcwSeen, "FCW never raised");
}

/* REQ-04 */
static void t_stages_never_skip(void)
{
  loop_result_t r = closed_loop(200.0, 0.0, 25.0, 0.0, 15.0);
  MJ_CHECK(r.stageOrderOk, "decel jumped over a stage or used an unknown value");
}

/* REQ-05 */
static void t_stops_before_stationary_lead(void)
{
  loop_result_t r = closed_loop(200.0, 0.0, 25.0, 0.0, 15.0);
  MJ_CHECK(r.minGap > 3.7, "min gap %.2f m (vehicle length 3.7 m)", r.minGap);
  MJ_CHECK(r.finalEgoV < 0.3, "ego still at %.2f m/s", r.finalEgoV);
}

/* REQ-06 */
static void t_release_after_stop(void)
{
  loop_result_t r = closed_loop(200.0, 0.0, 25.0, 0.0, 15.0);
  MJ_CHECK(!r.triggerAtEnd, "trigger still on after stop");
  MJ_CHECK(r.decelAtEnd == 0.0, "decel %.1f still applied after stop", r.decelAtEnd);
}

/* REQ-07 : ego 10 m/s -> FCW time 3.7 s, release at 1.2 x 3.7 = 4.44 s */
static void t_fcw_hysteresis(void)
{
  int k;
  fresh_ecu();
  step(3.7 + 30.0, 0.0, -10.0, 10.0);   /* TTC 3.0 -> enter FCW (one step lag) */
  step(3.7 + 30.0, 0.0, -10.0, 10.0);
  MJ_CHECK(rte_out.AEBTrigger == 1.0, "FCW not entered at TTC 3.0 s");
  for (k = 0; k < 10; k++) step(3.7 + 40.0, 0.0, -10.0, 10.0); /* TTC 4.0 */
  MJ_CHECK(rte_out.AEBTrigger == 1.0, "FCW dropped at TTC 4.0 s (< 4.44 s)");
  step(3.7 + 45.0, 0.0, -10.0, 10.0);  /* TTC 4.5 >= 4.44 */
  MJ_CHECK(rte_out.AEBTrigger == 0.0, "FCW not released at TTC 4.5 s");
}

/* REQ-08 */
static void t_no_trigger_adjacent_lane(void)
{
  loop_result_t r = closed_loop(200.0, 0.0, 25.0, -3.5, 15.0);
  MJ_CHECK(!r.anyTrigger, "AEBTrigger raised for lead in adjacent lane (y=-3.5)");
}

/* REQ-09 */
static void t_no_decel_adjacent_lane(void)
{
  loop_result_t r = closed_loop(200.0, 0.0, 25.0, -3.5, 15.0);
  MJ_CHECK(r.maxDecel == 0.0,
           "Deceleration %.1f m/s2 commanded for lead in adjacent lane (y=-3.5)",
           r.maxDecel);
}

/* REQ-10 */
static void t_every_step_writes_both_ports(void)
{
  int k;
  fresh_ecu();
  for (k = 0; k < 50; k++) step(100.0, 0.0, -5.0, 15.0);
  MJ_CHECK(rte_out.writeCount == 100U, "IWrite count %u, expected 100", rte_out.writeCount);
}

int main(int argc, char **argv)
{
  mj_run("REQ-01 no action when TTC > FCW time", t_no_action_when_far, 0, 0);
  mj_run("REQ-02 no action when lead pulls away", t_no_action_when_lead_pulls_away, 0, 0);
  mj_run("REQ-03 FCW comes before any braking", t_fcw_before_braking, 0, 0);
  mj_run("REQ-04 braking stages FCW-PB1-PB2-FB never skip", t_stages_never_skip, 0, 0);
  mj_run("REQ-05 stops before stationary lead (25 m/s, 200 m)", t_stops_before_stationary_lead, 0, 0);
  mj_run("REQ-06 release after standstill", t_release_after_stop, 0, 0);
  mj_run("REQ-07 FCW hysteresis 1.2x", t_fcw_hysteresis, 0, 0);
  mj_run("REQ-08 no trigger for adjacent-lane lead", t_no_trigger_adjacent_lane, 0, 0);
  mj_run("REQ-09 no deceleration for adjacent-lane lead", t_no_decel_adjacent_lane, 1, "AEB-12");
  mj_run("REQ-10 runnable writes both output ports every period", t_every_step_writes_both_ports, 0, 0);
  return mj_finish("AEB_Core_SWC.unit", argc > 1 ? argv[1] : NULL) ? 1 : 0;
}
